# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  client_tag: 'test_client'
  pool_tag: 'indy_pool'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: ClientImage
    displayName: Build client image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/libindy/ci/ubuntu.dockerfile'
        tags: |
          $(tag)
  - job: PoolImage
    displayName: Build Indy Pool image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/ci/indy-pool.dockerfile'
        tags: |
          $(pool_tag)