name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1 
    - name: Build docker image with indy pool inside
      uses: ./.github/actions/indy_pool
    - name: Run test
      run: echo "Not yet"
